[mypy]
python_version = 3.10
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
check_untyped_defs = True
ignore_missing_imports = True
exclude = (?x)(
    ^build/
    | ^dist/
    | ^\.mypy_cache/
  )

[mypy-regex]
ignore_missing_imports = True

[mypy-tiktoken]
ignore_missing_imports = True

[mypy-tokenizers.*]
ignore_missing_imports = True
