#ifndef uniqtoken
#define uniqtoken

/* Generated with cbindgen:0.29.4 */

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Return code indicating success.
 */
#define UNIQTOKEN_OK 0

/**
 * Return code indicating a null pointer argument.
 */
#define UNIQTOKEN_ERR_NULL_PTR -1

/**
 * Return code indicating an invalid UTF-8 file path.
 */
#define UNIQTOKEN_ERR_INVALID_PATH -2

/**
 * Return code indicating an I/O read failure.
 */
#define UNIQTOKEN_ERR_IO -3

/**
 * Return code indicating a JSON parsing or malformed vocabulary error.
 */
#define UNIQTOKEN_ERR_PARSE -4

/**
 * Return code indicating serialization failure.
 */
#define UNIQTOKEN_ERR_SERIALIZE -5

/**
 * Normal token type in llama.cpp.
 */
#define GGUF_TOKEN_TYPE_NORMAL 1

/**
 * Unknown token type in llama.cpp.
 */
#define GGUF_TOKEN_TYPE_UNKNOWN 2

/**
 * Control / special token type in llama.cpp.
 */
#define GGUF_TOKEN_TYPE_CONTROL 3

/**
 * User-defined token type in llama.cpp.
 */
#define GGUF_TOKEN_TYPE_USER_DEFINED 4

/**
 * Byte fallback token type in llama.cpp.
 */
#define GGUF_TOKEN_TYPE_BYTE 6

/**
 * Unset / null token ID in llama.cpp (equivalent to LLAMA_TOKEN_NULL = -1).
 */
#define LLAMA_TOKEN_NULL UINT32_MAX

/**
 * GGUF uint32 value type tag.
 */
#define GGUF_TYPE_UINT32 4

/**
 * GGUF int32 value type tag.
 */
#define GGUF_TYPE_INT32 5

/**
 * GGUF float32 value type tag.
 */
#define GGUF_TYPE_FLOAT32 6

/**
 * GGUF string value type tag.
 */
#define GGUF_TYPE_STRING 8

/**
 * GGUF array value type tag.
 */
#define GGUF_TYPE_ARRAY 9

/**
 * Return code indicating invalid UTF-8 input text.
 */
#define UNIQTOKEN_ERR_INVALID_UTF8 -6

/**
 * Return code indicating tokenization failure (e.g. disconnected lattice).
 */
#define UNIQTOKEN_ERR_ENCODE -7

/**
 * Opaque tokenizer handle. Always created by [`uniqtoken_create`] and
 * destroyed by [`uniqtoken_destroy`]; never constructed or inspected
 * directly from C.
 */
typedef struct UniqTokenHandle UniqTokenHandle;

/**
 * Exports a UniqToken vocabulary JSON file into binary GGUF v3 format.
 *
 * # Safety
 * Pointers `model_path`, `buffer_out`, and `size_out` must be non-null and valid.
 * The allocated buffer must be freed using `uniqtoken_free_buffer`.
 */
int32_t uniqtoken_export_gguf_vocab(const char *model_path, void **buffer_out, size_t *size_out);

/**
 * Deallocates the buffer returned by `uniqtoken_export_gguf_vocab` to prevent leaks.
 *
 * # Safety
 * `buffer` must have been allocated by `uniqtoken_export_gguf_vocab` with length `size`.
 */
void uniqtoken_free_buffer(void *buffer, size_t size);

/**
 * Builds a tokenizer handle from a `[[token, logprob, id], ...]` JSON
 * vocabulary (same shape as `demo_vocab.json`). IDs must be contiguous from
 * 0 and an `<|unk|>` entry must be present (unknown tokens resolve to it);
 * otherwise null is returned. The caller owns a successful handle and must
 * release it with [`uniqtoken_destroy`].
 *
 * # Safety
 * `vocab_json` must be non-null and point to a valid NUL-terminated C string.
 */
struct UniqTokenHandle *uniqtoken_create(const char *vocab_json);

/**
 * Encodes `text` (`text_len` bytes, need not be NUL-terminated) into token
 * IDs, writing a freshly allocated array to `*out_ids` with its length in
 * `*out_len`. Returns [`UNIQTOKEN_OK`] on success; the caller owns the array
 * and must release it with [`uniqtoken_free_tokens`].
 *
 * # Safety
 * `handle`, `out_ids`, and `out_len` must be non-null and valid; `text` must
 * point to `text_len` readable bytes.
 */
int32_t uniqtoken_encode(struct UniqTokenHandle *handle,
                         const char *text,
                         size_t text_len,
                         uint32_t **out_ids,
                         size_t *out_len);

/**
 * Releases an ID array produced by [`uniqtoken_encode`]. Accepts null.
 *
 * # Safety
 * `ids`/`len` must be the thin pointer + length produced by
 * [`uniqtoken_encode`] (a boxed-slice round-trip) and must not have been
 * freed before.
 */
void uniqtoken_free_tokens(uint32_t *ids, size_t len);

/**
 * Destroys a handle created by [`uniqtoken_create`]. Accepts null.
 *
 * # Safety
 * `handle` must have been allocated by [`uniqtoken_create`] and must not
 * have been destroyed before.
 */
void uniqtoken_destroy(struct UniqTokenHandle *handle);

#endif  /* uniqtoken */
